# scripts\snapshot.ps1
#
# Generates project-snapshot.md - a file tree plus contents of every
# file that matters for understanding the project, suitable for
# uploading to a Claude Project as context so future chats don't need
# the same files re-uploaded on every prompt.
#
# What it captures (in order of priority):
#   1. Top-level config (package.json, tsconfig, next.config, wrangler,
#      drizzle.config, eslint, postcss, components.json, .env.example,
#      .gitignore, .gitattributes)
#   2. Database layer (drizzle/*.sql migrations, drizzle/meta/_journal.json)
#   3. Shared library (lib/**/*.ts - schemas, actions, db, auth, env, logger)
#   4. App routes (app/**/*.tsx, app/**/*.ts - pages, layouts, actions)
#   5. Middleware (middleware.ts)
#   6. Components (components/**/*.tsx - UI primitives, feature components)
#   7. Scripts (scripts/*.ts - seed, other dev scripts)
#   8. Docs index (docs/README.md and top-level doc titles, not full contents)
#
# What it skips:
#   - node_modules, .next, .git, .wrangler, .open-next, coverage,
#     test-results, playwright-report, drizzle/meta/*.json (except _journal)
#   - Binary/image files (png, jpg, pdf, zip, sqlite, etc.)
#   - pnpm-lock.yaml (enormous, not useful for context)
#   - Files over 50 KB (with a note in the output)
#   - Anything that pushes the total output over 500 KB
#
# Usage (from project root):
#   pnpm snapshot              # normal - includes components
#   pnpm snapshot -Lean        # lean mode - skips components/ui/*
#
# Flags:
#   -Lean     Skip components/ui/*. Useful once the project grows and
#             snapshot size becomes a concern.
#
# Note on encoding: this file intentionally uses ASCII-only characters
# (plain hyphens, no em-dashes) because Windows PowerShell 5.x reads
# .ps1 files as the local code page by default and chokes on multi-byte
# UTF-8 characters without a BOM.

[CmdletBinding()]
param(
    [switch]$Lean
)

$ErrorActionPreference = "Stop"

# -- Setup ------------------------------------------------------
$projectRoot = Split-Path -Parent $PSScriptRoot
if (-not $projectRoot) { $projectRoot = (Get-Location).Path }
Set-Location $projectRoot

$out = Join-Path $projectRoot "project-snapshot.md"

# Size caps - tuned for Claude Project knowledge-base ingestion.
$MaxTotalBytes = 500KB
$MaxFileBytes  = 50KB

# -- Exclusion patterns -----------------------------------------
# Applied to full paths (case-insensitive). Any match means skip.
$excludedDirs = @(
    '\\node_modules\\',
    '\\\.next\\',
    '\\\.git\\',
    '\\\.wrangler\\',
    '\\\.open-next\\',
    '\\coverage\\',
    '\\test-results\\',
    '\\playwright-report\\',
    '\\\.turbo\\',
    '\\\.cache\\',
    '\\\.vercel\\'
)

# Extensions we never dump (binary or low-signal).
$excludedExtensions = @(
    'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'svg',
    'pdf', 'zip', 'tar', 'gz',
    'sqlite', 'sqlite-journal', 'db',
    'tsbuildinfo', 'log',
    'woff', 'woff2', 'ttf', 'eot'
)

# Specific filenames we never dump (large or low-signal).
$excludedFilenames = @(
    'pnpm-lock.yaml',
    'package-lock.json',
    'yarn.lock',
    'project-snapshot.md'
)

function Test-ShouldExclude {
    param([System.IO.FileInfo]$File)

    $path = $File.FullName

    foreach ($pattern in $excludedDirs) {
        if ($path -match $pattern) { return $true }
    }

    $ext = $File.Extension.TrimStart('.').ToLower()
    if ($excludedExtensions -contains $ext) { return $true }

    if ($excludedFilenames -contains $File.Name) { return $true }

    return $false
}

# -- Header -----------------------------------------------------
"# Consultway Ops - Project Snapshot" | Out-File $out -Encoding utf8
"" | Out-File $out -Append -Encoding utf8
"_Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')_" | Out-File $out -Append -Encoding utf8
if ($Lean) {
    "_Mode: **lean** (components/ui skipped)_" | Out-File $out -Append -Encoding utf8
}
"" | Out-File $out -Append -Encoding utf8
"This file is auto-generated by ``scripts/snapshot.ps1``. Do not edit by hand." | Out-File $out -Append -Encoding utf8
"Re-run ``pnpm snapshot`` after significant changes." | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8

# -- File tree --------------------------------------------------
"## File Tree" | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8
'```' | Out-File $out -Append -Encoding utf8

Get-ChildItem -Recurse -Force -File |
    Where-Object { -not (Test-ShouldExclude $_) } |
    ForEach-Object { $_.FullName.Replace("$projectRoot\", "") } |
    Sort-Object |
    Out-File $out -Append -Encoding utf8

'```' | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8

# -- Language detection for fenced code blocks ------------------
function Get-CodeFenceLanguage {
    param([string]$Path)

    $name = Split-Path $Path -Leaf
    $ext  = [System.IO.Path]::GetExtension($Path).TrimStart('.').ToLower()

    # Special filenames without useful extensions
    if ($name -eq '.env.example' -or $name -eq '.env')      { return 'env' }
    if ($name -eq '.gitignore')                             { return 'gitignore' }
    if ($name -eq '.gitattributes')                         { return 'gitattributes' }
    if ($name -eq 'Dockerfile')                             { return 'dockerfile' }
    if ($name -eq '_journal.json')                          { return 'json' }

    switch ($ext) {
        'tsx'   { return 'tsx' }
        'ts'    { return 'typescript' }
        'mts'   { return 'typescript' }
        'cts'   { return 'typescript' }
        'js'    { return 'javascript' }
        'mjs'   { return 'javascript' }
        'cjs'   { return 'javascript' }
        'jsx'   { return 'jsx' }
        'json'  { return 'json' }
        'jsonc' { return 'jsonc' }
        'css'   { return 'css' }
        'md'    { return 'markdown' }
        'yml'   { return 'yaml' }
        'yaml'  { return 'yaml' }
        'sql'   { return 'sql' }
        'sh'    { return 'bash' }
        'ps1'   { return 'powershell' }
        'html'  { return 'html' }
        default { return '' }
    }
}

# -- Helper: dump one file with size tracking -------------------
$script:totalBytes = 0
$script:dumped     = 0
$script:skipped    = @()

function Write-FileSection {
    param(
        [string]$RelativePath,
        [string]$AbsolutePath
    )

    if (-not (Test-Path $AbsolutePath)) {
        $script:skipped += "$RelativePath (not present)"
        return
    }

    $fileInfo = Get-Item $AbsolutePath
    if ($fileInfo.Length -gt $MaxFileBytes) {
        $sizeKb = [int]($fileInfo.Length / 1KB)
        $script:skipped += "$RelativePath (too large: $sizeKb KB)"
        return
    }

    # Total-size budget check - leave room for trailing sections.
    if ($script:totalBytes + $fileInfo.Length -gt $MaxTotalBytes) {
        $script:skipped += "$RelativePath (total-size budget exceeded)"
        return
    }

    $lang    = Get-CodeFenceLanguage -Path $RelativePath
    $content = Get-Content $AbsolutePath -Raw

    "### ``$RelativePath``"       | Out-File $out -Append -Encoding utf8
    ""                            | Out-File $out -Append -Encoding utf8
    "``````$lang"                 | Out-File $out -Append -Encoding utf8
    $content                      | Out-File $out -Append -Encoding utf8
    "``````"                      | Out-File $out -Append -Encoding utf8
    ""                            | Out-File $out -Append -Encoding utf8

    $script:totalBytes += $fileInfo.Length
    $script:dumped++
}

# -- Helper: dump every file under a directory matching a filter -
# Previously I used Get-ChildItem with patterns like 'lib\**\*.ts',
# but PowerShell does NOT expand ** recursively in -Path. The literal
# ** made those calls return zero matches. This version does the right
# thing: -Path is the directory, -Filter is the extension glob, and
# -Recurse walks every level.
function Write-DirectoryFiles {
    param(
        [string]$SectionTitle,
        # One or more { Directory = '...'; Filter = '*.ts' } entries.
        # Example: @{ Directory = 'lib'; Filter = '*.ts' }
        [hashtable[]]$Sources,
        # Relative-path glob(s) to skip (e.g., 'components\ui\*').
        [string[]]$ExcludePatterns = @()
    )

    "## $SectionTitle" | Out-File $out -Append -Encoding utf8
    ""                 | Out-File $out -Append -Encoding utf8

    $matched = @()
    foreach ($src in $Sources) {
        $dir    = $src.Directory
        $filter = $src.Filter

        if (-not (Test-Path $dir)) { continue }

        $found = Get-ChildItem -Path $dir -Filter $filter -Recurse -File `
                               -ErrorAction SilentlyContinue

        foreach ($f in $found) {
            $rel  = $f.FullName.Replace("$projectRoot\", "")
            $skip = $false
            foreach ($ex in $ExcludePatterns) {
                if ($rel -like $ex) { $skip = $true; break }
            }
            if ((Test-ShouldExclude $f) -or $skip) { continue }
            $matched += $f
        }
    }

    # De-duplicate and sort for deterministic output.
    $matched = $matched | Sort-Object FullName -Unique

    foreach ($f in $matched) {
        $rel = $f.FullName.Replace("$projectRoot\", "")
        Write-FileSection -RelativePath $rel -AbsolutePath $f.FullName
    }

    if (-not $matched) {
        "_No files present in this section yet._" | Out-File $out -Append -Encoding utf8
        ""                                         | Out-File $out -Append -Encoding utf8
    }
}

# -- Section 1: top-level config --------------------------------
# These live at the project root and set up the whole stack.
"## Top-Level Config" | Out-File $out -Append -Encoding utf8
""                    | Out-File $out -Append -Encoding utf8

$topLevelFiles = @(
    'package.json',
    'tsconfig.json',
    'next.config.ts',
    'wrangler.jsonc',
    'drizzle.config.ts',
    'eslint.config.mjs',
    'postcss.config.mjs',
    'components.json',
    'middleware.ts',
    '.env.example',
    '.gitignore',
    '.gitattributes',
    'pnpm-workspace.yaml'
)

foreach ($f in $topLevelFiles) {
    Write-FileSection -RelativePath $f -AbsolutePath (Join-Path $projectRoot $f)
}

# -- Section 2: database (drizzle) ------------------------------
# Migrations and journal tell the reader the exact schema history.
Write-DirectoryFiles -SectionTitle "Database - Migrations and Schema History" -Sources @(
    @{ Directory = 'drizzle'; Filter = '*.sql' },
    @{ Directory = 'drizzle\meta'; Filter = '_journal.json' }
)

# -- Section 3: shared lib --------------------------------------
# The heart of the business logic: schemas, actions, db, auth, utilities.
# This is the one that was broken before - lib/db/*.ts and lib/auth/*.ts
# were being silently skipped.
Write-DirectoryFiles -SectionTitle "Shared Library (lib/)" -Sources @(
    @{ Directory = 'lib'; Filter = '*.ts' },
    @{ Directory = 'lib'; Filter = '*.tsx' }
)

# -- Section 4: app routes --------------------------------------
# Every page, layout, and server action.
Write-DirectoryFiles -SectionTitle "App Routes (app/)" -Sources @(
    @{ Directory = 'app'; Filter = '*.tsx' },
    @{ Directory = 'app'; Filter = '*.ts'  }
) -ExcludePatterns @('*\globals.css')

# Also include globals.css once (it defines our design tokens).
Write-FileSection -RelativePath 'app\globals.css' `
                  -AbsolutePath (Join-Path $projectRoot 'app\globals.css')

# -- Section 5: components --------------------------------------
# In lean mode we skip components/ui/* (shadcn primitives rarely change).
$componentExcludes = @()
if ($Lean) {
    $componentExcludes = @('components\ui\*')
}
Write-DirectoryFiles -SectionTitle "Components" -Sources @(
    @{ Directory = 'components'; Filter = '*.tsx' },
    @{ Directory = 'components'; Filter = '*.ts'  }
) -ExcludePatterns $componentExcludes

# -- Section 6: scripts -----------------------------------------
# Seed scripts and other dev automation. Only top-level *.ts files
# (no recursion needed here - scripts/ is flat).
Write-DirectoryFiles -SectionTitle "Scripts" -Sources @(
    @{ Directory = 'scripts'; Filter = '*.ts'  },
    @{ Directory = 'scripts'; Filter = '*.mts' }
)

# -- Section 7: docs index --------------------------------------
# Just the titles of each doc - full contents would blow the budget.
"## Docs Index" | Out-File $out -Append -Encoding utf8
""              | Out-File $out -Append -Encoding utf8

$docFiles = @()
if (Test-Path 'docs') {
    $docFiles = Get-ChildItem -Path 'docs' -Filter '*.md' -File -ErrorAction SilentlyContinue |
                Sort-Object Name
}

if ($docFiles) {
    "_Full docs are in_ ``docs/`` _- listing filenames here only. Ask for specific docs when needed._" |
        Out-File $out -Append -Encoding utf8
    ""                  | Out-File $out -Append -Encoding utf8
    foreach ($doc in $docFiles) {
        $rel = $doc.FullName.Replace("$projectRoot\", "")
        "- ``$rel``" | Out-File $out -Append -Encoding utf8
    }
    "" | Out-File $out -Append -Encoding utf8
} else {
    "_No docs present._" | Out-File $out -Append -Encoding utf8
    ""                    | Out-File $out -Append -Encoding utf8
}

# -- Section 8: footer - skipped files report -------------------
if ($script:skipped.Count -gt 0) {
    "## Skipped Files" | Out-File $out -Append -Encoding utf8
    ""                 | Out-File $out -Append -Encoding utf8
    "The following files were skipped (size budget, binary, or not yet present):" |
        Out-File $out -Append -Encoding utf8
    ""                 | Out-File $out -Append -Encoding utf8
    foreach ($s in $script:skipped) {
        "- $s" | Out-File $out -Append -Encoding utf8
    }
    "" | Out-File $out -Append -Encoding utf8
}

# -- Console summary --------------------------------------------
$finalSizeKb = [int]((Get-Item $out).Length / 1KB)
$budgetKb    = [int]($MaxTotalBytes / 1KB)

Write-Host ""
Write-Host "Snapshot written to project-snapshot.md" -ForegroundColor Green
Write-Host "  Files dumped: $($script:dumped)"
Write-Host "  Files skipped: $($script:skipped.Count)"
Write-Host "  Output size: $finalSizeKb KB (budget: $budgetKb KB)"
if ($Lean) {
    Write-Host "  Mode: LEAN (components/ui excluded)" -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Next step: upload project-snapshot.md to your Claude Project knowledge base."
Write-Host ""
