# scripts\snapshot.ps1
#
# Generates project-snapshot.md — a file tree + contents of key files,
# suitable for uploading to a Claude Project as context so future chats
# don't need the same files re-uploaded on every prompt.
#
# Usage (from project root):
#   pnpm snapshot
# or:
#   pwsh scripts\snapshot.ps1

$ErrorActionPreference = "Stop"

# Resolve project root (parent of scripts/)
$projectRoot = Split-Path -Parent $PSScriptRoot
if (-not $projectRoot) { $projectRoot = (Get-Location).Path }
Set-Location $projectRoot

$out = Join-Path $projectRoot "project-snapshot.md"

# Header
"# Consultway Ops — Project Snapshot" | Out-File $out -Encoding utf8
"" | Out-File $out -Append -Encoding utf8
"_Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')_" | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8
"This file is auto-generated by ``scripts/snapshot.ps1``. Do not edit by hand." | Out-File $out -Append -Encoding utf8
"Re-run ``pnpm snapshot`` after significant changes." | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8

# ── File tree ──────────────────────────────────────────────────
"## File Tree" | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8
'```' | Out-File $out -Append -Encoding utf8
Get-ChildItem -Recurse -Force |
    Where-Object {
        $_.FullName -notmatch '\\node_modules\\' -and
        $_.FullName -notmatch '\\\.next\\' -and
        $_.FullName -notmatch '\\\.git\\' -and
        $_.FullName -notmatch '\\\.wrangler\\' -and
        $_.FullName -notmatch '\\\.open-next\\' -and
        $_.FullName -notmatch '\\coverage\\' -and
        $_.FullName -notmatch '\\test-results\\' -and
        $_.FullName -notmatch '\\playwright-report\\' -and
        $_.Name -notmatch '\.(png|jpe?g|gif|webp|ico|pdf|zip|sqlite|sqlite-journal|tsbuildinfo)$'
    } |
    ForEach-Object { $_.FullName.Replace("$projectRoot\", "") } |
    Sort-Object |
    Out-File $out -Append -Encoding utf8
'```' | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8

# ── File contents ──────────────────────────────────────────────
# Add files here as the project grows. Order matters — put the
# highest-signal files first (what someone most needs to understand
# the project should be near the top).
$filesToDump = @(
    # Config & project metadata
    "package.json",
    "tsconfig.json",
    "next.config.ts",
    "eslint.config.mjs",
    "postcss.config.mjs",
    "components.json",
    "wrangler.jsonc",
    ".env.example",
    ".gitignore",
    # App entry points
    "app\layout.tsx",
    "app\page.tsx",
    "app\globals.css",
    # Shared lib
    "lib\utils.ts",
    # UI primitives (first one as reference)
    "components\ui\button.tsx"
)

"## Key Files" | Out-File $out -Append -Encoding utf8
"" | Out-File $out -Append -Encoding utf8

$dumped = 0
foreach ($file in $filesToDump) {
    if (Test-Path $file) {
        $ext = [System.IO.Path]::GetExtension($file).TrimStart('.').ToLower()
        switch ($ext) {
            "tsx"    { $lang = "tsx" }
            "ts"     { $lang = "typescript" }
            "mjs"    { $lang = "javascript" }
            "js"     { $lang = "javascript" }
            "json"   { $lang = "json" }
            "jsonc"  { $lang = "jsonc" }
            "css"    { $lang = "css" }
            "md"     { $lang = "markdown" }
            "yml"    { $lang = "yaml" }
            "yaml"   { $lang = "yaml" }
            default  { $lang = "" }
        }
        # Dotfiles and `.env.example` have no extension from Path's POV
        if ($file -eq ".env.example") { $lang = "env" }
        if ($file -eq ".gitignore")   { $lang = "gitignore" }

        "### ``$file``" | Out-File $out -Append -Encoding utf8
        "" | Out-File $out -Append -Encoding utf8
        "``````$lang" | Out-File $out -Append -Encoding utf8
        (Get-Content $file -Raw) | Out-File $out -Append -Encoding utf8
        "``````" | Out-File $out -Append -Encoding utf8
        "" | Out-File $out -Append -Encoding utf8
        $dumped++
    }
    else {
        Write-Host "  (skipped — not yet present) $file" -ForegroundColor DarkGray
    }
}

$size = [int]((Get-Item $out).Length / 1KB)
Write-Host ""
Write-Host "✓ Snapshot written to project-snapshot.md" -ForegroundColor Green
Write-Host "  Files included: $dumped / $($filesToDump.Count)"
Write-Host "  Size: $size KB"
Write-Host ""
Write-Host "Next step: upload project-snapshot.md to your Claude Project knowledge base."
